font:
    resource: "@FontBundle/Resources/config/routing.yml"
    prefix:   /
utilisateur:
    resource: "@UtilisateurBundle/Resources/config/routing.yml"
    prefix:   /

page:
    resource: "@PageBundle/Resources/config/routing.yml"
    prefix:   /


