# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    utilisateur.form.registration:
        class: UtilisateurBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: utilisateur_registration }